spring.application.name=demo

weather.api.key=aee301ecb626c55cc9d253e2a72f6aa0
weather.api.base-url=https://api.openweathermap.org/data/2.5

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m